### PR TITLE
sort result list

### PR DESCRIPTION
**Pull request by sennahLessert**
#4  

i didn't found the correct parameter to sort the result list remotely so i did it clientside

### CODE REVIEW

**Comment by akramkazmi71** [comment]
API call logic has changed, due to that a conflict has occurred, can you please resolve the conflict and update the solving logic as per the changes occurred in #15 .

**Comment by sennahLessert** [comment]
Yes of course

**Comment by sennahLessert** [comment]
done

**Comment by akramkazmi71** [comment]
Can you please look into this issue https://deploy-preview-17--hacktober-xrepos.netlify.com/ 
In you code the API displays only 28 entries instead of 30, and it does not show the complete list. Just refer the preview link with the original one.

**Comment by sennahLessert** [comment]
yeah i'll fix that

**Comment by sennahLessert** [comment]
DONE!

**Comment by akramkazmi71** [comment]
Thank you for your contribution. :100: :+1:

**Pull request merged**
