### PR TITLE
remove text selection

### PR DESCRIPTION
**Pull request by alggs**
css adjustments to deselect text on page

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
@alggs Can you explain a bit more about this PR. What exactly it does?

**Comment by alggs** [comment]
Hello @arshadkazmi42 !
This code makes it impossible for the user to select page text, enabling a better user experience.

**Comment by arshadkazmi42** [comment]
> Hello @arshadkazmi42 !
> This code makes it impossible for the user to select page text, enabling a better user experience.

I was able to select all the texts before. But can't select anything in this build.
You can check it here
https://deploy-preview-30--hacktober-xrepos.netlify.com/

I tried in firefox

**Comment by arshadkazmi42** [comment]
Inactive PR.

**Pull request closed without merging**
